### ISSUE TITLE
Describing how a task/event can be scheduled for different date

### ISSUE THREAD

**Issue by PeUzunov** [PeUzunov/QA-Fundamentals-Team-Project#12]
To be added to test cases: User shouldnt be able to drag and drop events from one date to an other in order to change event date. 
Expected scenario if user try to drag'n'drob event to other date/time - an error message to apeear and warn him about that.
The only way to do so is through "edit" event tab.

**Comment by PeUzunov** [comment]
For better UX the drag'n'drob fucntion will be developed. Expected scenario:
user selects a event by "grabbing" it and dragging it to a different location  - different date/time. the event willl should be deleted from his original location and visible ot the new locataion, the new date/time. this will change the event date/time.

**Comment by 100yanov** [comment]
All cases Described. Refer to SRS and Test tases filed. version 1.0
